# Generated by Django 2.2.2 on 2019-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='1890882009252084a336c03-8c4a-4bff-904e-c3a365ff28ba2019-07-16-181830800707', max_length=400, null=True, unique=True),
        ),
    ]
