# Generated by Django 2.2.2 on 2019-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190716_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='196885991953407567de396-ce05-4e87-8751-d852fb9c9a152019-07-16-181835448014', max_length=400, null=True, unique=True),
        ),
    ]
