# Generated by Django 2.2.2 on 2019-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190716_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ppaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='21592550817629774719e33-b3ba-437e-82f6-64dbdf354e042019-07-16-182204321730', max_length=400, null=True, unique=True),
        ),
    ]
