# Generated by Django 2.2.2 on 2019-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190727_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='164228184373151e692051c-1a22-44f4-8889-ab8b3bc715ac2019-07-29-161006260037', max_length=400, null=True, unique=True),
        ),
    ]
