# Generated by Django 2.2.13 on 2020-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190729_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='28549758221697b834fec0-c39b-42a3-a922-3004c1e46df02020-10-20-174802009372', max_length=400, null=True, unique=True),
        ),
    ]
