# Generated by Django 2.2.18 on 2021-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201020_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='450659237841398b9364ff2-a162-4560-bb09-6562765f72752021-07-10-175124538149', max_length=400, null=True, unique=True),
        ),
    ]
