# Generated by Django 2.2.18 on 2021-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210711_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='25000794458081121e7fc8a-41d5-4b33-8346-ee792bc0d3af2021-07-11-204222045087', max_length=400, null=True, unique=True),
        ),
    ]
