# Generated by Django 2.2.18 on 2021-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210711_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='704338261418700f95151-8a3f-4d09-994d-19f2f63cfc542021-07-11-205822416516', max_length=400, null=True, unique=True),
        ),
    ]
