# Generated by Django 2.2.18 on 2021-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210711_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='76290815746302884544013-5746-48de-a8cf-e32dd99a0f172021-07-12-222651649959', max_length=400, null=True, unique=True),
        ),
    ]
