# Generated by Django 2.2.18 on 2021-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210712_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='813537817204921be62f88b-70b3-4367-827a-d27cbb54b6be2021-07-14-211917228954', max_length=400, null=True, unique=True),
        ),
    ]
