from django.contrib import admin
from django.urls import path, include
import datetime
from main.views import *
from users.views import *
from django.contrib.auth import views as auth_views
from users.models import *

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('consulting/', consulting),
    path('consulting-ru/', consulting_ru),
    path('trial-ua/', trial_ua, name='trial-ua'),
    path('trial-es/', trial_es, name='trial-es'),
    path('trial-fr/', trial_fr, name='trial-fr'),
    path('trial-ru/', trial_ru, name='trial-ru'),
    path('trial-en/', trial_en, name='trial-en'),
    path('trial/', trial, name='trial'),
    path('trial-tk/', trial, name='trial-tk'),
    path('trial-i/', trial, name='trial-i'),
    path('trading-ru-g-ig/', trading_ru_g, name='trading-ru-g'),
    path('reviews/', reviews, name='reviews'),
    path('underconstruction/', ud, name='ud'),
    path('business/', business, name='business'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('process-payment/<str:course>/',
         process_payment,
         name='process_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
    path('', main, name='main'),
    path('path/<str:slug>/', post_detail, name='post_detail_url'),
    path('departments/', departments, name='departments'),
    path('junior-studio/', junior_studio, name="junior-studio"),
    path('psy-finance/', psy_finance, name="psy-finance"),
    path('trading/', trading, name='trading'),
    path('t/', trading_ru_g, name='trading-ru-g-t'),
    path('trading-ru/', trading_ru, name='trading-ru'),
    path('trading-en/', trading_en, name='trading-en'),
    path('trading-ua/', trading_ua, name='trading-ua'),
    path('trading-es/', trading_es, name='trading-es'),
    path('trading-fr/', trading_fr, name='trading-fr'),
    path('trading-ru-i/', trading_ru_i, name='trading-ru-i'),
    path('trading-ru-g/', trading_ru_g, name='trading-ru-g'),
    path('trading-fr-i/', trading_fr_i, name='trading-fr-i'),
    path('trading-es-i/', trading_es_i, name='trading-es-i'),
    path('trading-en-i/', trading_en_i, name='trading-en-i'),
    path('trading-ua-i/', trading_ua_i, name='trading-ua-i'),
    path('trading-fr-g/', trading_fr_g, name='trading-fr-g'),
    path('trading-es-g/', trading_es_g, name='trading-es-g'),
    path('trading-en-g/', trading_en_g, name='trading-en-g'),
    path('trading-ua-g/', trading_ua_g, name='trading-ua-g'),
    path('developing/', developing, name="developing"),
    path('contact-us/', contact_us, name="contact-us"),
    path('fuel-additives/', fuel_additives, name="fuel-additives"),
    path('hedge-fund/', hedge_fund, name='hedge-fund'),
    path('websites-developing/',
         websites_developing,
         name="websites-developing"),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='loginn'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),

    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('payment-done/', shop_views.payment_done, name='payment_done'),
    # path('payment-cancelled/', shop_views.payment_canceled, name='payment_cancelled'),
    # path(
    #     'buy-license/<str:app_name_id>/<str:pricing_id>/<int:period>/<int:max_machines_amount>/',
    #     shop_views.buy_license),
    # path('login',
    #      auth_views.LoginView.as_view(template_name='shop/login.html',
    #                                   extra_context={'next': 'profile'}),
    #      name='shop-login'),
    # path(
    #     'buy-license/<str:app_name_id>/<str:pricing_id>/<int:period>/<int:max_machines_amount>/',
    #     shop_views.buy_license),
]
