# Generated by Django 2.2.18 on 2021-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=20000)),
                ('name_id', models.CharField(blank=True, max_length=50)),
                ('pricing', models.CharField(blank=True, max_length=5000)),
                ('faq', models.CharField(blank=True, max_length=10000)),
                ('logo', models.CharField(blank=True, max_length=1000)),
                ('screenshots', models.CharField(blank=True, max_length=5000)),
                ('videos', models.CharField(blank=True, max_length=5000)),
                ('views_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
