# Generated by Django 2.2.18 on 2021-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='private_creds',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
