# Generated by Django 2.2.13 on 2021-03-21 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40)),
                ('additional_info', models.CharField(blank=True, max_length=1000)),
                ('expiration', models.IntegerField(default=0)),
                ('creation_date', models.DateField(blank=True, verbose_name='Date created')),
                ('max_machines_limit', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(blank=True, max_length=1000)),
                ('info', models.CharField(blank=True, max_length=1000)),
                ('last_login', models.DateTimeField(blank=True, verbose_name='Last login time')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellapp.License')),
            ],
        ),
    ]
