# Generated by Django 2.2.13 on 2021-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
