# Generated by Django 2.2.13 on 2021-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0002_machine_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
