# Generated by Django 2.2.13 on 2021-03-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0003_license_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='max_machines_limit',
            field=models.IntegerField(default=3),
        ),
    ]
