# Generated by Django 2.2.18 on 2021-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0004_auto_20210327_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
