# Generated by Django 2.2.18 on 2021-07-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0005_license_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='is_custom',
        ),
        migrations.AlterField(
            model_name='license',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.App'),
        ),
    ]
